version: '2'
services:

    nginx:
        image: nginx:mainline
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx:/etc/nginx:ro
            - ./static:/usr/src/app/static
            - ./frontend/dist:/usr/src/app/frontend
        restart: unless-stopped